# el servidor genera una sesion temporal el cual se usara  en
# futuras peticiones, se requiere un nombre de usuario y contrasena validos
[login]
request = {Usuario: str, Contrasena: str}
type = "POST"

[teacher_course_list]
response = [
    {
        CursoNombre: str,
        HoraInicio: str,
        HoraFin: str,
        Salon: str,
        Pabellon: str,
        state: str,
    }
]
type = "GET"

[teacher_mark]
request = {CursoNombre: str, HoraInicio: str, HoraFin: str}
response = {success: bool}
type = "POST"

[logout]
request = {}
response = {success: bool}
type = "POST"
